l1=["himanshu", "anam", "raj", "colleuge"]
#print(l1)
print(len(l1))
print(l1[1:3])
print(l1[-1])
l2=["apple", "banana"]
l1.append("banana")
#print(l1,l2)
#print(l1)
#l1.sort()
print(l1)
l1.copy()
print(l1)
print(l1.pop())
print(l1.count("anam"))
l1.remove("himanshu")
print(l1)
l1.insert(2,23)
print(l1)
l1.extend([34,32])
print(l1)
l1.reverse()
print(l1)
l=[23,4,567,7,8]
print(l)
l.sort(reverse=True )
print(l)
l.sort()
print(l)
print(max(l))
print(min(l))
print(l)
l[2]=56
print(l)
del l[1]
print(l)